spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/site1?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 3306
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
